name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"

      # Build frontend
      - name: Build frontend
        run: |
          cd front
          yarn
          yarn build

      # Build backend binaries
      - name: Build backend binaries
        run: VERSION=${{ github.ref_name }} back/build.sh

        # Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            -t ghcr.io/${{ github.repository }}:latest \
            --build-arg BINARY_PATH=back/anemone-${{ github.ref_name }}-linux-amd64/anemone .

        # Push Docker image
      - name: Push Docker image
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}:latest
